### PR TITLE
Initial vite server creation and react components framework built

### PR DESCRIPTION
**Pull request by Cora-Du**
@Lenaciousd @matthewtboyle @JGon26 

Here is our initial pull request on the creation of our web app. Please review and verify we have our framework built out in a manner that we can each work on our designated widgets and features accordingly.

https://trello.com/c/fX9d5lFO

### CODE REVIEW

**Comment by Lenaciousd** [comment]
Should we add ESLint or React Testing Library?

**Comment by matthewtboyle** [comment]
> Should we add ESLint or React Testing Library?

Is React Testing Library something we will use along side of Jest, or in place of?

**Comment by JGon26** [comment]
> Should we add ESLint or React Testing Library?

-yes we should have a consensus on starting testing frameworks before we merge

**Comment by Lenaciousd** [comment]
> > Should we add ESLint or React Testing Library?
> 
> Is React Testing Library something we will use along side of Jest, or in place of?

I think we can use them together

**Comment by Cora-Du** [comment]
Added eslint and updated files to follow now. Also added react testing library as a dependency.

**Review by matthewtboyle — APPROVED** [review]

**Review by JGon26 — APPROVED** [review]
Looks great!

**Pull request merged**
